package com.xuleyan.finals.dal.mapper;

import com.xuleyan.finals.dal.pojo.Account;
import com.xuleyan.finals.dal.pojo.AccountCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    long countByExample(AccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int deleteByExample(AccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int insertSelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    List<Account> selectByExample(AccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int updateByExample(@Param("record") Account record, @Param("example") AccountCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int updateByPrimaryKeySelective(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_account
     *
     * @mbg.generated Fri Jul 16 22:59:30 CST 2021
     */
    int updateByPrimaryKey(Account record);
}