package com.xuleyan.finals.dal.pojo;

import java.util.Date;

public class GoodsSecondsKill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_seconds_kill.id
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_seconds_kill.user_id
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_seconds_kill.gmt_create
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_seconds_kill.id
     *
     * @return the value of goods_seconds_kill.id
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_seconds_kill.id
     *
     * @param id the value for goods_seconds_kill.id
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_seconds_kill.user_id
     *
     * @return the value of goods_seconds_kill.user_id
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_seconds_kill.user_id
     *
     * @param userId the value for goods_seconds_kill.user_id
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_seconds_kill.gmt_create
     *
     * @return the value of goods_seconds_kill.gmt_create
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_seconds_kill.gmt_create
     *
     * @param gmtCreate the value for goods_seconds_kill.gmt_create
     *
     * @mbg.generated Sat Jul 17 11:16:24 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}